name: Playwright Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install
      
      - name: Run Playwright tests
        run: npx playwright test || true # Чтобы GitHub Actions не падал при ошибках

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-report.json
          
      - name: Upload screenshot
        uses: actions/upload-artifact@v4
        with:
          name: mobile-screenshot
          path: test-screenshot.png
